### ISSUE TITLE
No such native module with 1.0+

### ISSUE THREAD

**Issue by Rytiss** [nexe/nexe#208]
(not quite sure if duplicate of #199)

I dynamically download module files from the internet and load them:
`var m = require('./tmp-module.js');`

This used to work with 0.4.2 but no longer works with 1.0+, resulting in an "No such native module" error. I'm using Node 5.8.0 as latest stable has compilation errors as noted in #207.

**Comment by jaredallard** [comment]
Hi, this is due to browserify. A workaround is to use `GLOBAL.require` for now

**Comment by vilic** [comment]
@jaredallard I tried to monkey patched NativeModule.require and it seems to be working.

```js
if (!NativeModule.exists(id)) {
  return global.require(id);
}
```

**Comment by marianogenovese** [comment]
Hi!, there is a workaround for this issue? I have the same issue here, to load a js file using require.

**Comment by JamesMGreene** [comment]
Suffering from the same problem here with `zmq`.

**Comment by calebboyd** [comment]
Fixed in `nexe@beta` Let me know if you still have issues

**Comment by JamesMGreene** [comment]
See #335 for more.
