### ISSUE TITLE
NEXE COMPILER - RANDOM BINARY CODE

### ISSUE THREAD

**Issue by henriquegmatos** [nexe/nexe#788]
Dear,

I humbly get in touch with you over an issue. I already researched everything I could and analyzed the XENE codes to try to solve it and I haven't been able to do it so far.

The problem:
Whenever I compile the same nodejs application with NEXE I get a different binary code. I perform an md5sum on the binary file and it gives me different hashes. I need a solution that ensures that Nexe always generates the binary code with the same hash.

This is for an electronic election application on the WEB. For audit traceability, it is essential that the compiled code always has the same hash.

Testing:
I carried out extensive tests and I could see that machines with only 1 processor have the same hashes more often, they are less random. This may imply that multiple asynchronous thead processes are generating different orders during the process of compiling the application modules. This is just a guess. The more CPUs and more components, the more different hashing results I get.

Attempts for solutions:
1-I tried to use a machine with only 1 CPU
2-Includes the line "process.env.UV_THREADPOOL_SIZE = 1;" in the files: ~ / .nvm / versions / node / v10.17.0 / lib / node_modules / nexe / index.js; : ~ / .nvm / versions / node / v10.17.0 / lib / node_modules / nexe / lib / compiler.js; ~ / .nvm / versions / node / v10.17.0 / lib / node_modules / nexe / node_modules / resolve-dependencies / lib / worker-runtime.js

The only thing that really did deduce the randomization of the hashes was attempt number 1

My request: HELP

I imagine that this demand may be frequent in needs of this type that need to guarantee the integrity of the application code.

I thank you for your patience and any attempt to help my problem.

Plataform: Debian 10, NODEJS 10.17. NEXE 3.3.2

Best regards,

**Comment by calebboyd** [comment]
This should be fixed in nexe 3.3.3. Please update and try again

**Comment by henriquegmatos** [comment]
Thanks for the quick reply..

I performed the upgrade to 3.3.3 and several tests. And unfortunately I can't have the same hash. Below are the commands used and the results.

~# nexe -b -i index.js -o index.exe --verbose --make="-j1" ; md5sum index.exe
ℹ nexe 3.3.3
✔ Downloading Node.jssource from: https://nodejs.org/dist/v10.17.0/node-v10.17.0.tar.gz
✔ Already downloaded...
✔ Compiling result
✔ Writing result to file
✔ Entry: 'index.js' written to: index.exe
✔ Finished in 90.262s
13e5a86d28a9368fa2109020dde882fd  index.exe

~# nexe -b -i index.js -o index.exe --verbose --make="-j1" ; md5sum index.exe
ℹ nexe 3.3.3
✔ Downloading Node.jssource from: https://nodejs.org/dist/v10.17.0/node-v10.17.0.tar.gz
✔ Already downloaded...
✔ Compiling result
✔ Writing result to file
✔ Entry: 'index.js' written to: index.exe
✔ Finished in 87.033s
e41b074ccc342c39dcb27bcf91f3955f  index.exe

**Comment by calebboyd** [comment]
I realized that 3.3.3 didn't get the bump I thought it did. Fixed with 3.3.4. Sorry!

**Comment by henriquegmatos** [comment]
Is version 3.3.4 already available? I used the npm upgrade nexe command and upgraded to 3.3.3

If it is not released, do you have a date for version 3.3.4 ?.

**Comment by calebboyd** [comment]
Yeah its available
```
~> npm dist-tag nexe                       
latest: 3.3.4
beta: 4.0.0-beta.10
...
```

**Comment by henriquegmatos** [comment]
Is nexe 3.3.4 compatible with node 10.17?

Now I got it

~# nexe -b index.js
ℹ nexe 3.3.4
✔ nexe 3.3.4
✔ Finished in 0.376s
TypeError: ((intermediate value)(intermediate value)(intermediate value) || []).flat is not a function
    at nodeModuleGlobs (/root/.nvm/versions/node/v10.17.0/lib/node_modules/nexe/node_modules/resolve-dependencies/lib/file.js:25:101)
    at Object.hasModuleGlobs (/root/.nvm/versions/node/v10.17.0/lib/node_modules/nexe/node_modules/resolve-dependencies/lib/file.js:11:12)
    at Loader.load (/root/.nvm/versions/node/v10.17.0/lib/node_modules/nexe/node_modules/resolve-dependencies/lib/loader-pool.js:94:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by calebboyd** [comment]
Shooot. Okay. I'll take a look

**Comment by calebboyd** [comment]
Try 3.3.5 😳

**Comment by henriquegmatos** [comment]
I'm using node 10.17

Now chance to this

ℹ nexe 3.3.5
✔ nexe 3.3.5
✔ Finished in 2.223s
TypeError: Object.fromEntries is not a function
    at resolve (/root/.nvm/versions/node/v10.17.0/lib/node_modules/nexe/node_modules/resolve-dependencies/lib/resolve.js:15:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by calebboyd** [comment]
I changed the typescript target version to support the older version of node and updated the code. The tests are passing and it looks to be good. Please confirm! 3.3.6

**Comment by henriquegmatos** [comment]
Ok, now with version 3.3.6 it is working with node 10.17. However, the nexe is still generating different binaries with each compilation. Therefore it generates different hashes. There is a solution?

# nexe --make="-j1"  -i index.js -o index.exe ; md5sum index.exe ; ls -l | grep index.exe
ℹ nexe 3.3.6
✔ Already downloaded...
✔ Compiling result
✔ Entry: 'index.js' written to: index.exe
✔ Finished in 16.233s
3c98b1fc1c5c683ad4dbd991f64944c8  index.exe
-rwxr-xr-x   1 root root 54223406 Jun 26 14:23 index.exe
# nexe --make="-j1"  -i index.js -o index.exe ; md5sum index.exe ; ls -l | grep index.exe
ℹ nexe 3.3.6
✔ Already downloaded...
✔ Compiling result
✔ Entry: 'index.js' written to: index.exe
✔ Finished in 15.968s
bf26f38d4a2545bddc911b50004e4961  index.exe
-rwxr-xr-x   1 root root 54223407 Jun 26 14:24 index.exe
# nexe --make="-j1"  -i index.js -o index.exe ; md5sum index.exe ; ls -l | grep index.exe
ℹ nexe 3.3.6
✔ Already downloaded...
✔ Compiling result
✔ Entry: 'index.js' written to: index.exe
✔ Finished in 16.905s
b995d6574c26e6816ff9ecd635a0a0bc  index.exe
-rwxr-xr-x   1 root root 54223406 Jun 26 14:24 index.exe

**Comment by calebboyd** [comment]
If you could make a small reproduction that might help. I can't reproduce this issue
```
code/test > nexe index.js -o -r package.json out -t 12.10.0 && shasum out
ℹ nexe 3.3.6
✔ Included 1 file(s). 0.002 MB
✔ Already downloaded...
✔ Compiling result
✔ Entry: 'out' written to: true
✔ Finished in 0.403s
80b86578c13d4b7d5ecc23b879fd8530cf6139b0  out
code/test > nexe index.js -o -r package.json out -t 12.10.0 && shasum out
ℹ nexe 3.3.6
✔ Included 1 file(s). 0.002 MB
✔ Already downloaded...
✔ Compiling result
✔ Entry: 'out' written to: true
✔ Finished in 0.41s
80b86578c13d4b7d5ecc23b879fd8530cf6139b0  out
code/test > nexe index.js -o -r package.json out -t 12.10.0 && shasum out
ℹ nexe 3.3.6
✔ Included 1 file(s). 0.002 MB
✔ Already downloaded...
✔ Compiling result
✔ Entry: 'out' written to: true
✔ Finished in 0.448s
80b86578c13d4b7d5ecc23b879fd8530cf6139b0  out
```

**Comment by henriquegmatos** [comment]
Dear Caleb,

in fact the problem occurs when the application has many components and the computer has many cpus as well. However, even with 1 CPU the problem occurs. Please try to test with an application with several nodejs modules installed. I tested with a small program and only after compiling 30 times a different hash appears. But with larger applications, different hashes will appear more often.

**Comment by henriquegmatos** [comment]
[guiaperguntas.tar.gz](https://github.com/nexe/nexe/files/4839166/guiaperguntas.tar.gz)

I'm using this sample to tests

there is a batch file loop.sh to make compiled file, create hashes.  It will abort what the hash is diferent.

**Comment by calebboyd** [comment]
`nexe@next` (4.0.0-beta.11) should have this issue resolved. Thanks for pointing it out!

**Comment by henriquegmatos** [comment]
Hi Caleb,

Did you get simulate the problem? 
it is very important to me that the problem has become clear to you. I would like to thank you for your attention to this problem. thank you for your kindness and look forward to your success.

Best regards

**Comment by calebboyd** [comment]
It's fixed in next. See my previous comment. You can install it with 

`npm I nexe@next`

**Comment by henriquegmatos** [comment]
Hi Caleb,

I do upgraded to nexe@next but the problem is the same. :( 

root@debian-nodes:~/Projetos-Nodejs/guiaperguntas# ./loop.sh
node v12.10.0
ℹ nexe 4.0.0-beta.11
✔ Already downloaded...
✔ Compiling result
✔ Entry: 'index.js' written to: index.exe
✔ Finished in 5.517s
nexe -b -i index.js -o index.exe
Ok - Same HASH = 8420bdf62c0ee09be637af133a4188e9

node v12.10.0
ℹ nexe 4.0.0-beta.11
✔ Already downloaded...
✔ Compiling result
✔ Entry: 'index.js' written to: index.exe
✔ Finished in 5.36s
nexe -b -i index.js -o index.exe
Ok - Same HASH = 8420bdf62c0ee09be637af133a4188e9

node v12.10.0
ℹ nexe 4.0.0-beta.11
✔ Already downloaded...
✔ Compiling result
✔ Entry: 'index.js' written to: index.exe
✔ Finished in 5.657s
nexe -b -i index.js -o index.exe
Ok - Same HASH = 888d1b97ec51c19f54a45c069567897e
Aborting : Different Hash!
root@debian-nodes:~/Projetos-Nodejs/guiaperguntas#

**Comment by henriquegmatos** [comment]
I had a different hash after 74 compilations using just one CPU

56 - 50179163 Jun 27 20:48 index.exe   8420bdf62c0ee09be637af133a4188e9
57 - 50179163 Jun 27 20:48 index.exe   8420bdf62c0ee09be637af133a4188e9
58 - 50179163 Jun 27 20:48 index.exe   8420bdf62c0ee09be637af133a4188e9
59 - 50179163 Jun 27 20:48 index.exe   8420bdf62c0ee09be637af133a4188e9
60 - 50179163 Jun 27 20:48 index.exe   8420bdf62c0ee09be637af133a4188e9
61 - 50179163 Jun 27 20:49 index.exe   8420bdf62c0ee09be637af133a4188e9
62 - 50179163 Jun 27 20:49 index.exe   8420bdf62c0ee09be637af133a4188e9
63 - 50179163 Jun 27 20:49 index.exe   8420bdf62c0ee09be637af133a4188e9
64 - 50179163 Jun 27 20:49 index.exe   8420bdf62c0ee09be637af133a4188e9
65 - 50179163 Jun 27 20:49 index.exe   8420bdf62c0ee09be637af133a4188e9
66 - 50179163 Jun 27 20:50 index.exe   8420bdf62c0ee09be637af133a4188e9
67 - 50179163 Jun 27 20:50 index.exe   8420bdf62c0ee09be637af133a4188e9
68 - 50179163 Jun 27 20:50 index.exe   8420bdf62c0ee09be637af133a4188e9
69 - 50179163 Jun 27 20:50 index.exe   8420bdf62c0ee09be637af133a4188e9
70 - 50179163 Jun 27 20:50 index.exe   8420bdf62c0ee09be637af133a4188e9
71 - 50179163 Jun 27 20:51 index.exe   8420bdf62c0ee09be637af133a4188e9
72 - 50179163 Jun 27 20:51 index.exe   8420bdf62c0ee09be637af133a4188e9
73 - 50179163 Jun 27 20:51 index.exe   8420bdf62c0ee09be637af133a4188e9
74 - 50179163 Jun 27 20:51 index.exe   772f597a43819ad3b64863c3f724e77c

**Comment by calebboyd** [comment]
Hmm. I think I've narrowed it down. Initially it was just a file order problem, which is fixed. There is concurrency accessing file descriptors of included files to determine the size. And I'm doing that at the same time that I'm building the file index for access. So the offsets end up being out of order when the size stat comes back whenever.

**Comment by henriquegmatos** [comment]
I see. do you believe that a solution for this case would be possible?

**Comment by henriquegmatos** [comment]
Hi Caleb,

Do you have any expectations about that?

Does this project have a donation channel? We are motivated to participate in some way in this improvement.

best regards

**Comment by calebboyd** [comment]
I've added a link [here](https://github.com/nexe/nexe/blob/master/.github/FUNDING.yml). I may not have time until after the upcoming holiday.

**Comment by henriquegmatos** [comment]
I see. Ok.  Are you in USA? Do you mean 4th July's holiday?.

Thank you.

**Comment by henriquegmatos** [comment]
Hello Caleb,

How was the holiday? 

And about Nexe, any good news?

best regards.

**Comment by calebboyd** [comment]
You can try it with nexe@next
https://github.com/nexe/nexe/commit/2b261728b4616c7f0e604cf9fb14e995d244363a

**Comment by henriquegmatos** [comment]
Dear Caleb

I believe that this time the hash problem has been solved. I did a lot of tests and the compiler is generating the same binary file. Congratulations!!!! 

However, another problem appeared. When using the -r parameter for resource inclusion, the compilation is completed without error, but runtime errors occur.

I am attaching a small example. Please compile using the run-me.sh batch file.

basically the build command used is:

nexe -b -i index.js -o index.exe -r ./myfile.txt

trying to run i got the following error:
[henrique2.zip](https://github.com/nexe/nexe/files/4900028/henrique2.zip)

ction () {process .__ nexe = {
         ^

SyntaxError: Unexpected token {
    at Module._compile (internal / modules / cjs / loader.js: 723: 23)
    at _third_party_main.js: 38: 36
    at NativeModule.compile (internal / bootstrap / loaders.js: 364: 7)
    at Function.NativeModule.require (internal / bootstrap / loaders.js: 176: 18)
    at process.nextTick (internal / bootstrap / node.js: 249: 22)
    at process._tickCallback (internal / process / next_tick.js: 61: 11)

I hope that the attached file and the attempt to explain can help you solve this point.

Thank you.

**Comment by calebboyd** [comment]
Welp!. It was a basically a rewrite, so I'm not surprised I missed something. 

I forgot to set the size for resource files.
Fixed here: https://github.com/nexe/nexe/commit/e51b6b21a619b13ce0c7c841afef4dbe65b4c667#diff-5c7b68e345d4a34bf7aa66eceae8c709R37

released beta.14

**Comment by henriquegmatos** [comment]
Caleb,

The  beta.14 solved the problem, thanks.  

But now we have a problem compiling the pdfkit module. This module compiled without problems in version 3.3.6 of NEXE. Now with the beta.14 version we have the error below.

ℹ nexe 4.0.0-beta.14
✔ Included 183 file(s)
✔ Already downloaded...
✔ Compiling result
✔ Entry: 'index.js' written to: index.exe
✔ Finished in 9.186s
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/henrique/node_modules/unicode-properties/data.trie'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.readFileSync (/home/henrique/index.exe:219:55)
    at Object.<anonymous> (/home/henrique/node_modules/unicode-properties/unicode-properties.cjs.js:139:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/henrique/node_modules/fontkit/index.js:24:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/henrique/node_modules/pdfkit/js/pdfkit.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by calebboyd** [comment]
The module unicode-properties is trying to read the filesystem, for node_modules/unicode-properties/data.trie if you include it, it will work

**Comment by calebboyd** [comment]
To clarify, The breaking change from 3-4 is that files are only included if they're statically analyzable. 

The options for addressing this are:
 - **Manual inclusion:**: (explicitly set filesystem available to your packaged code) (default v4 beta)
 - **Resolve all:** The resolve-dependencies options could be exposed to resolve `all` files, in all referenced packages (v3). 
 - **Smarter/different analysis:** `__dirname` and readfile api's + string literals could be analyzed for presence/inclusion

The current state is manual inclusion. The second option could be available until the third option (least surprise) could be implemented.

Thoughts?
