### ISSUE TITLE
Build failed since node version 12.16.X on Linux x64

### ISSUE THREAD

**Issue by alxproject** [nexe/nexe#763]
**What happened**: using node 12.16.0+ the build fail on linux

**What you expected to happen**: the build to success

**How to reproduce it (as minimally and precisely as possible)**:
test.js:
`console.log('test nexe');`
trying to build:
`nexe test.js --build --verbose -o test`
with node 12.15.0- : success
with node 12.16.0+: failed with the next messages
```
../src/node.cc:849:45: warning: left operand of comma operator has no effect [-Wunused-value]
                                             errors,
                                             ^~~~~~
../src/node.cc:850:45: warning: right operand of comma operator has no effect [-Wunused-value]
                                             kAllowedInEnvironment);
                                             ^~~~~~~~~~~~~~~~~~~~~
../src/node.cc:850:66: error: expected ‘;’ before ‘)’ token
                                             kAllowedInEnvironment);
                                                                  ^
                                                                  ;
../src/node.cc:850:67: warning: right operand of comma operator has no effect [-Wunused-value]
                                             kAllowedInEnvironment);
                                                                   ^
../src/node.cc:857:43: warning: left operand of comma operator has no effect [-Wunused-value]
                                           errors,
                                           ^~~~~~
../src/node.cc:858:43: warning: right operand of comma operator has no effect [-Wunused-value]
                                           kDisallowedInEnvironment);
                                           ^~~~~~~~~~~~~~~~~~~~~~~~
../src/node.cc:858:67: error: expected ‘;’ before ‘)’ token
                                           kDisallowedInEnvironment);
                                                                   ^
                                                                   ;
../src/node.cc:858:68: warning: right operand of comma operator has no effect [-Wunused-value]
                                           kDisallowedInEnvironment);
```

**Anything else we need to know?**:
checking the changs that nexe do on the node source code find that nexe change the file node.cc
node 12.15.0 original:
`const int exit_code = ProcessGlobalArgs(&env_argv, nullptr, errors, true);`
`const int exit_code = ProcessGlobalArgs(argv, exec_argv, errors, false);`

node 12.15.0 changed by nexe:
`const int exit_code = 0;//ProcessGlobalArgs(&env_argv, nullptr, errors, true);`
`const int exit_code = 0;//ProcessGlobalArgs(argv, exec_argv, errors, false);`

this change works well on node 12.15.0 and earlier but in node 12.16.0+ the changes produces syntax error caused by breaklines on the source

node 12.16.0+ original:
```
const int exit_code = ProcessGlobalArgs(&env_argv,	
                                            nullptr,	
                                            errors,	
                                            kAllowedInEnvironment);
```
node 12.15.0 changed by nexe:
```
const int exit_code = 0;//ProcessGlobalArgs(&env_argv,
                                            nullptr,
                                            errors,
                                            kAllowedInEnvironment);

```
the changes made by nexe generates a syntax error for the one line comment on a multi line function

**Environment**: Linux x64
- Platform(OS/Version): Debian 10, Ubuntu 18.04, Ubuntu 19.04, Ubuntu 20.04
- Host Node Version: 12.15.0, 12.16.3
- Target Node Version: 12.16.3
- Nexe version: 3.3.2
- Python Version: 2.7.16

**Comment by naikus** [comment]
@alxproject 
The problem is here. Maybe I can create a pull request if i get the time. I'm facing this similar issue with node 12.17.0 LTS on linux 20.04

https://github.com/nexe/nexe/blob/928b8134a7c988432f0af716014d6083b3cc00b6/src/patches/disable-node-cli.ts#L16

**Comment by alxproject** [comment]
Thanks, the beta versión compile without problem
