### ISSUE TITLE
Another issue with package websocket, related to debug package

### ISSUE THREAD

**Issue by jeffrson** [nexe/nexe#479]
Working on Windows 10, Python 2.7.14.

package.json:
```
{
  "name": "nexe_test",
  "version": "1.0.0",
  "description": "nexe_test",
  "main": "src/test.js",
  "license": "ISC",
  "dependencies": {
    "debug": "^3.1.0",
    "websocket": "^1.0.26"
  }
}

```
src\test.js:
```
console.log("1")
const webSocket = require("websocket");
console.log("2")

```
From `nexe --verbose -t 9.11.1` a file `test.exe` is created which results in this error:
```
1
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'ms'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at u (...\test.exe:4247:1092)
    at f (...\test.exe:4247:1430)
    at c (...\test.exe:4247:2731)
    at b.require (...\test.exe:4247:3327)
    at Object.<anonymous> (...\test.exe:240:20)
    at c (...\test.exe:4247:3565)

```
