### ISSUE TITLE
Dynamic resources not resolving requires in 4.0.0-beta.18

### ISSUE THREAD

**Issue by nohack** [nexe/nexe#910]
**What happened**:
When I include a dynamic resource, the files required in the dynamic resource are not included and the executable fails with _Cannot find module_ error.This occurs in 4.0.0-beta.18 where as the same code works in 3.3.3.

The dynamic resource is p1/m1.js and it requires p2/m2.js.

**What you expected to happen**:
Output m2 to console on running executable.
I am curious to understand which changes caused this issue in 4.0.0-beta.18, if possible the specific commit as we can debug better issues going forward.
Is it because of **resolve-dependencies** version change between 4.0.0-beta.18 and v3.3.3.

**How to reproduce it (as minimally and precisely as possible)**:
Clone the [repo](https://github.com/nohack/nexe-requirebug-v3-v4beta)

1) 3.3.3
z/build3
docker run nexe-requirebug-v3-v4beta-3
Output: m2

2) 4.0.0-beta.18
z/build4
docker run nexe-requirebug-v3-v4beta-4.beta.18
Output: 

```internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '../p2/m2'
Require stack:
- /app/p1/m1.js
- /app/p1/index.js
- /app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/p1/m1.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/p1/m1.js', '/app/p1/index.js', '/app/index.js' ]
}
```

**Anything else we need to know?**:

**Environment**:
- Platform(OS/Version):
linux
- Host Node Version:
12.15.0
- Target Node Version:
12.15.0
- Nexe version:
3.3.3 and 4.0.0-beta.18

**Comment by calebboyd** [comment]
This is by design and was why the change was major version bump. If the expected application files are not statically analyzable from the given entrypoint then they should be explicitly called out and passed to `-r`
