### ISSUE TITLE
This repository has a ton of the exact same issues listed

### ISSUE THREAD

**Issue by kimboslice99** [nexe/nexe#1073]
Is anyone still managing this repo?

#1050, #1030, #1028, #954 etc are all the same issue, nexe's core purpose `🎉 create a single executable out of your node.js apps` fails to do so.

Is this broken or what? -r "./node_modules/**/*" does nothing to help, just bloats the file size.

**Comment by NotMikeDEV** [comment]
After wasting days trying to figure out this issue... [This seems to be the explanation](https://github.com/nexe/nexe/pull/1063)
You need to use the latest version from git. Of course the real question is how long will it take for this fix to make it to npm? Latest beta release was over a year ago...

**Comment by NotMikeDEV** [comment]
I was unable to get it working with node 18 or 20.
After several days of frustration I managed to get it working with the latest git commit, and I assumed that was the issue. I thought I had solved it...
However, after cleaning out my dev environment (which is docker based) and starting clean from the latest commit, it failed :( I was unable to figure out what the issue was...

I ended up finding a fork of the pkg project which supports the latest node release.

**Comment by DeRidderJonas** [comment]
I was having the same issue as described above and found out that nexe does include the code in the executable but still looks for the files in the working directory. I'm working in node 18.19.0

@calebboyd Since you added the "more inforation needed" tag, I'll add some examples:

# Single file
index.js (D:\src)
```
console.log("Hello World!");
```
> nexe . -i index.js -o test.exe

results in test.exe

If we run test.exe in D:\src, we get the following:
`Hello World!`
and all is good.

However if we move the test.exe to a different folder (in this case D:\test) and run test.exe, we get the following:
```
node:internal/modules/cjs/loader:1137
  throw err;
  ^

Error: Cannot find module 'D:\test\index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.19.0
```

But if we add an empty index.js file next to the test.exe, we once again have our `Hello World!`.

# Multiple files

Image we have multiple files:
D:/src/index.js
```
const controller = require("./controllers/controller");
controller.foo();
```
D:/src/controllers/controller.js
```
function foo(){console.log("bar");}
module.exports = { foo }
```
 
1. Creating the exe will work as long as it remains in the same folder as the original code. 
1. Once we move the exe, it will break, asking for the original files (but in the new folder, respecting the relative paths in the require so `require("controllers/controller.js")` in `D:\test` will go looking for `D:\test\controllers\controller.js`.
1. Creating the exact same folder structure but with empty files will restore the exe

In my larger project where I'm using typescript, then run nexe in the dist folder containing the regular js files, I have also found that the modules I've created and import using require("./foo/bar"), are usually not included in the project. But if I specifically include them using `nexe . -r "**/*"`, they will be included and the exe does run when moved if the empty files are once again added to the test folder.

# npm packages
- If you `require` and npm installed packages, then copy your node_modules folder next to the moved executable, it will be fixed.
- I didn't test out my theory using any npm installed modules and clearing their content but I assume if you were to copy the node_modules folder then cleared all files and left them empty, the moved executable will work again

# Conclusion
The code is included (even though you might have to include them using the `-r`) but the executable will still go looking for the files even though it doesn't care about what the content of those files might be.

**Comment by K-ETFreeman** [comment]
same for me
[calebboyd](https://github.com/calebboyd) added the [os-windows](https://github.com/nexe/nexe/labels/os-windows) label
does this mean, it works on linux just fine? only windows issue?

**Comment by yuniruyuni** [comment]
in linux and mac-os same issue has happen
