### ISSUE TITLE
"Error: Cannot find module"

### ISSUE THREAD

**Issue by tratch** [nexe/nexe#659]
**Is this a BUG or a FEATURE REQUEST?:** 

**What happened:**
Running 
```
compile({
      name: 'myExe',
      input: 'dist/lib/index.exe.js',
      target: 'windows-x64-8.9.4',
      build: false,
      output: exePath,
      resources: [],
      loglevel: 'verbose',
    });
```
Compiles the executable fine, however when I run the executable I get a "Error: Cannot find module".

I recently updated nexe from 2.0.0-rc.26 to the latest version (3.3.2) and tried the next version (4.0.0-beta.1) but it cannot find any modules included in node_modules

**What you expected to happen:**

I would expect the modules kept in node_modules to be found by my application code.

**How to reproduce it (as minimally and precisely as possible):**

```
compile({
      name: 'myExe',
      input: 'dist/lib/index.exe.js',
      target: 'windows-x64-8.9.4',
      build: false,
      output: exePath,
      resources: [],
      loglevel: 'verbose',
    });
```

- Platform(OS/Version):
Windows 10
- Host Node Version:
v8.14.0
- Target Node Version:
windows-x64-8.9.4
- Nexe version:
3.3.2 and 4.0.0-beta.1
- Python Version:

**Comment by tratch** [comment]
Issue is also happening in nexe 3.0.0. I double checked and confirmed it is indeed working in nexe 2.0.0-rc.26. The leads me to believe that an assumption has changed between v 2.x.x and v 3.x.x.

Does it read the package.json file differently?

**Comment by danawoodman** [comment]
If I do a `nexe -t macos -n myapp bin/myapp.js` right now it generates a binary but as soon as I move it to another directory it fails. If I use the pkg project it works as expected. What do I need to do to tell the build to be static and not expecting a particular file system path?

**Comment by Jozsan** [comment]
I got the same problem

**Comment by danawoodman** [comment]
@calebboyd any suggestions as to why this is happening?

**Comment by khoiminhpham** [comment]
> If I do a `nexe -t macos -n myapp bin/myapp.js` right now it generates a binary but as soon as I move it to another directory it fails. If I use the pkg project it works as expected. What do I need to do to tell the build to be static and not expecting a particular file system path?

I got the same issue, 0t windows work fine, but -t alpine and -t linux return missing module when compiled alone in different dir
