### ISSUE TITLE
Regression in de9894c from nexe@3.3.2 to nexe@4.0.0-beta.1 – module not found

### ISSUE THREAD

**Issue by aral** [nexe/nexe#755]
## What happened

App that compiles with nexe@3.3.2 fails with a module not found error in nexe@4.0.0-beta.1. The regression was introduced in commit de9894c and most likely is in the resolve-dependencies module (between versions 2.2.3 and 3.0.2).

## What you expected to happen

For the compilation to succeed on both.

## How to reproduce it

```sh
git clone https://source.small-tech.org/site.js/app site.js
cd site.js
npm i

# This will use Nexe 3.3.2
npm run install-locally

site --version

# 👆 It works.

npm i nexe@4.0.0-beta.1
npm run install-locally

site --version
```

The following error is thrown:

```
Error: Cannot find module './serve'
Require stack:
- /usr/local/bin/node_modules/@small-tech/instant/lib/index.js
- /usr/local/bin/index.js
- /usr/local/bin/bin/commands/version.js
- /usr/local/bin/bin/site.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/local/bin/node_modules/@small-tech/instant/lib/index.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/bin/node_modules/@small-tech/instant/lib/index.js',
    '/usr/local/bin/index.js',
    '/usr/local/bin/bin/commands/version.js',
    '/usr/local/bin/bin/site.js'
  ]
}
```

## Environment

- Platform(OS/Version): Pop!_OS 19.10 (~Ubuntu 19.10)
- Host Node Version: 12.16.2
- Target Node Version: 12.16.2
- Nexe version: @3.3.2 (works), @4.0.0-beta-1 (does not work)
- Python Version: 2.7.17 & 3.7.5

**Comment by aral** [comment]
In case it helps, I just ran the following code from the root of Site.js:

```js
const { resolve } = require('resolve-dependencies')

;(async () => {
  const { entries, files } = await resolve({ entries: './index.js', loadContent: false })
  console.log(`${Object.keys(files).length} entries resolved`)
})()
```

With resolve-dependencies @ 2.2.3 (as used in Nexe @3.3.2, which works), I get:

```
1006 entries resolved
```

With resolve-dependencies @3.0.2 (as used in Nexe @4.0.0-beta-1 onwards, which doesn’t work), I get:

```
780 entries resolved
```

So there is definitely a behaviour difference between them.

**Comment by calebboyd** [comment]
This has been fixed in the latest `nexe@next`

LMK if you see any issues!

**Comment by aral** [comment]
You’re a star, @calebboyd, works like a charm – thank you! :) :beers:
