### ISSUE TITLE
Problem with local module reference

### ISSUE THREAD

**Issue by luizwbr** [nexe/nexe#657]
**Is this a BUG or a FEATURE REQUEST?:** 
BUG, maybe ?

**What happened:**
I tried to create an app from main js file, where package.json references another module in a folder.

**What you expected to happen:**
Create a executable file.

**How to reproduce it (as minimally and precisely as possible):**
I have 2 packages:
- my-setup
_package.json:_
```
{
	"name": "my-setup",
	"version": "1.0.0",
	"bin": "./src/app.js",
	"main": "app.js",
	"dependencies": {
		"commons": "file:../commons",
	}
}
```
- commons
_package.json:_
```
{
	"name": "commons",
	"version": "1.0.0",
	"description": "Common Lib",
	"main": "src/index.js",
	"private": true,
	"dependencies": {
		"colors": "~1.1.2",
		"sequelize": "~4.33.4",
		"sqlite3": "~4.0.9",
		"tar": "~4.4.10"
	}
}
```

I tried to run this command in my-setup folder.
` nexe src/app.js  --target linux-x64 --name my-setup --enableNodeCli true --fakeArgv true --logLevel debug `

The my-setup file was created, but when I try to run, appear this error:
```
module.js:549
    throw err;
    ^

Error: Cannot find module 'commons'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/teste/src/app.js:19:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

```

**Anything else we need to know?:** 
I can already do this using other binary file generators like PKG

**Environment**

- Platform(OS/Version): Ubuntu 19.04
- Host Node Version: v8.10.0
- Target Node Version: v8.10.0
- Nexe version: 3.3.2
- Python Version: 2.7.16

**Comment by tratch** [comment]
I'm experiencing the same behaviour with nexe 3.3.2 as well as nexe 4.0.0-beta.1.

Everything was working fine with nexe 2.0.0-rc.26

**Comment by adam-cyclones** [comment]
I also have had this problem, My best guess is that I shoud publish my dep to npm, or perhaps use direct github git+ url.

**Comment by calebboyd** [comment]
closing in favor of #717
